version: "3.8"
services:
  postgres:
    image: postgres:10
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: pg_isready -U xpaste
      interval: 1s
      timeout: 1s
      retries: 30

  xpaste:
    image: xpaste:latest
    build:
      context: .
    env_file:
      - .env
    volumes:
      - xpaste-sock:/var/run
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    image: nginx:1.27.0
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - xpaste-sock:/var/run
    ports:
      - 80:80
    depends_on:
      - xpaste

volumes:
  xpaste-sock:
