---
- name: "Setting up server and deploy an app"
  hosts: all
  become: true

  vars:
    app_name: "app"
    db_user: exam
    db_password: exam
    db_name: exam

  pre_tasks:
    - name: "Update apt repo and cache"
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: "Install packages for Postgres"
      apt: "name={{ item }} state=present"
      with_items:
        - postgresql
        - postgresql-contrib
        - python3-pip
        - python3-dev
        - python3-venv
        - python3-psycopg2
        - acl

    - name: "Install Python packages for Postgres"
      pip: "name={{ item }}  state=present"
      with_items:
        - psycopg2-binary

  roles:
    - geerlingguy.nginx
    - postgresql
    - app
    - nginx
